sudo chown -R www-data MPOS/logs
sudo chown -R www-data MPOS_alpha/logs
sudo chown -R www-data MPOS_bbq/logs
sudo chown -R www-data MPOS_casino/logs
sudo chown -R www-data MPOS_coin42/logs
sudo chown -R www-data MPOS_cosmos/logs
sudo chown -R www-data MPOS_diamond/logs
sudo chown -R www-data MPOS_digibyte/logs
sudo chown -R www-data MPOS_digital/logs
sudo chown -R www-data MPOS_flappy/logs
sudo chown -R www-data MPOS_grand/logs
sudo chown -R www-data MPOS_klondike/logs
sudo chown -R www-data MPOS_lotto/logs
sudo chown -R www-data MPOS_neo/logs
sudo chown -R www-data MPOS_noble/logs
sudo chown -R www-data MPOS_redd/logs
sudo chown -R www-data MPOS_solar/logs
sudo chown -R www-data MPOS_tag/logs
sudo chown -R www-data MPOS_template/logs
sudo chown -R www-data MPOS_tesla/logs
sudo chown -R www-data MPOS_usde/logs
